##
# Test auto-generated by Typus.
# Use it to test the extended admin functionality.
##
require 'test_helper'

class Admin::ActivitiesControllerTest < ActionController::TestCase

  # Replace this with your real tests.
  test "the truth" do
    flunk 'Not done testing yet.'
  end

end
